### ISSUE TITLE
Opening game via Launcher while offline will crash

### ISSUE THREAD

**Issue by jdl96** [HumanGamer/WPlusIssues#64]
Pressing the "Play Game" button in the Launcher while offline will cause the following error to occur:

```
************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: oldValue
   at System.String.Replace(String oldValue, String newValue)
   at WonderlandPlusLauncher.MainForm.LaunchGame()
   at WonderlandPlusLauncher.MainForm.btnLaunch_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by ALEXM99999** [comment]
Fixed in commit 02b810b6 of launcher.
